### PR TITLE
TurtleShroom Productions Proudly Presents: V1.4 Update

### PR DESCRIPTION
**Pull request by TurtleShroom**
As promised a long time ago, I have ported my updates and fixes to this Mod to the latest version.

### CODE REVIEW

**Comment by emipa606** [comment]
Seems to be some conflicts with this PR as well. Can you look into that?

**Comment by emipa606** [comment]
Any news on these conflicts?

**Comment by TurtleShroom** [comment]
> Any news on these conflicts?

My apologies, I have been busy. I am not sure how to resolve them absent manually copying and pasting each line.

**Comment by TurtleShroom** [comment]
It says that the  conflicts are too complex to resolve.

**Comment by emipa606** [comment]
Nice job, published in fa33304

Minor fixes:
- Added conditional patchoperation to TSP_LetMeDoItForYou

**Pull request merged**
